default['jenkins']['home'] = '/var/jenkins_home'
default['jenkins']['SSH_user']='jenkins'
default['jenkins']['SSH_user_homedir']='/var/jenkins_home'
default['jenkinsadmin']['file'] = "#{node['jenkins']['home']}/users/jenkinsadmin/config.xml"
default['jenkinsadmin']['fullName'] = 'Jenkins Admin'
default['jenkinsadmin']['email'] = 'email@email.com'
default['jenkins']['user'] = 'jenkinsadmin'
default['jenkins']['password'] = 'Jazzadmin01'
default['server']['privateip']='10.0.0.59'
default['slave']['publicip']='10.0.0.33'
default['client']['url'] = "http://#{node['server']['privateip']}/jnlpJars/jenkins-cli.jar"
default['client']['jar'] = "#{node['jenkins']['SSH_user_homedir']}/cookbooks/jenkins/files/default/jenkins-cli.jar"
default['node']['configurescript'] = "#{node['jenkins']['SSH_user_homedir']}/cookbooks/jenkins/files/node/create-node.sh"
default['authfile']="#{node['jenkins']['SSH_user_homedir']}/cookbooks/jenkins/files/default/authfile"
default['jenkins']['scriptApprovalfile']="#{node['jenkins']['SSH_user_homedir']}/cookbooks/jenkins/files/scriptapproval/scriptApproval.xml"
default['jenkins']['scriptApprovalfiletarget']="#{node['jenkins']['home']}/scriptApproval.xml"
default['scm']='bitbucket'
default['scmelb']='jazz-bitbucketelb.us-east-1.elb.amazonaws.com.blah'
default['scmpath']="#{node['scmelb']}/scm"
default['jenkinselb']='localhost:8080'
default['region']='us-east-1'
default['git_branch']='master'
default['jenkins']['SES-defaultSuffix']='defaultSuffixValue'
default['jenkins']['SES-smtpAuthUsername']='smtpAuthUsernameValue'
default['jenkins']['SES-smtpAuthPassword']='smtpAuthPasswordValue'
default['jenkins']['SES-smtpHost']='email-smtp.us-east-1.amazonaws.com'
default['jenkins']['SES-useSsl']='true'
default['jenkins']['SES-smtpPort']='25'
